/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./cb/**/*.html",
    "./cb/**/*.js",
    "./_Y2xpY2tiYW5r/**/*.html",
    "./_Y2xpY2tiYW5r/**/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Nunito",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
        ],
        serif: ["Lora", "ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
        montserrat: ["Montserrat", "sans-serif"],
        lora: ["Lora", "serif"],
        roboto: ["Roboto", "sans-serif"],
        "roboto-condensed": ["Roboto Condensed", "sans-serif"],
        oswald: ["Oswald", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      colors: {
        primary: "#B08D57",
        "header-red": "#d0190d",
        "primary-hover": "#C49A6B",
        "primary-dark": "#9c7a4a",
        "upsell-green": "#42a001",
        "upsell-green-2": "#43bf0e",
        "upsell-yellow": "#fef002",
        "upsell-red": "#fc3d21",
        "upsell-slate": "#e2f4f0",
        "upsell-ivory": "#fffeec",
        "upsell-buttercream": "#e7e4b1",
        "upsell-teal": "#07695c",
        "pure-red": "#ff0000",
        "header-red": "#d0190d",
        "upsell-red-2": "#d0190d",
      },
    },
  },
  plugins: [],
};
